spring.application.name=what-can-we-play

#JDBC URL for SQLite Database file (will create if doesnt exist)
spring.datasource.url=jdbc:sqlite:whatCanWePlay.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect 
spring.sql.init.mode=always

